### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by redbaty** [WPF-Forge/Forge.Forms#3]
- [ ] Environment
- [ ] Initial XAML dynamic grid
- [ ] Return types for dialogs
- [ ] docs, lots of them
- [ ] XML package
- [ ] More demos, visual designer
